# Generated by Django 4.0 on 2022-02-02 14:41

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_description', models.CharField(max_length=100, verbose_name='توضیح کوتاه')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='FactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='مقدار')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جزئیات فاکتور',
                'verbose_name_plural': 'جزئیات فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام پروژه')),
                ('description', models.TextField(verbose_name='توضیحات پروژه')),
                ('accessibility', models.CharField(blank=True, choices=[('private', 'خصوصی'), ('public', 'عمومی'), ('only_customer', 'فقط کارفرما')], max_length=13, null=True, verbose_name='دسترسی')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='تاریخ شروع')),
                ('end_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'شنبه'), ('sunday', 'یک شنبه'), ('monday', 'دو شنبه'), ('tuesday', 'سه شنبه'), ('wednesday', 'چهار شنبه'), ('thursday', 'پنجشنبه'), ('friday', 'جمعه')], max_length=20, verbose_name='روز')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت شروع کار')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='ساعت پایان کار')),
                ('accessibility', models.CharField(blank=True, choices=[('private', 'خصوصی'), ('public', 'عمومی'), ('only_customer', 'فقط کارفرما')], max_length=13, null=True, verbose_name='دسترسی')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'روز کاری',
                'verbose_name_plural': 'روزهای کاری',
            },
        ),
    ]
