# Generated by Django 4.0 on 2022-01-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='accessibility',
            field=models.CharField(blank=True, choices=[('private', 'خصوصی'), ('public', 'عمومی'), ('only_customer', 'فقط کارفرما')], max_length=13, null=True, verbose_name='دسترسی'),
        ),
    ]
