# Generated by Django 4.0 on 2022-02-02 11:22

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_workday'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='نام')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='مقدار')),
                ('amount', models.BigIntegerField(verbose_name='قیمت')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جزئیات فاکتور',
                'verbose_name_plural': 'جزئیات فاکتور ها',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=100, verbose_name='توضیح کوتاه')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده / نشده')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='projects.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
            },
        ),
    ]
