# Generated by Django 4.0 on 2022-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_ref_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='authority',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
