# Generated by Django 4.0 on 2022-01-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employee_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(auto_created='AOW6Jo', blank=True, max_length=6, verbose_name='شناسه مشتری'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(auto_created='#a6fHE', blank=True, max_length=6, verbose_name='شناسه کارمندی'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='شماره تلفن'),
        ),
    ]
