# Generated by Django 4.0 on 2022-01-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, default='zJ!YuF', max_length=6, verbose_name='شناسه مشتری'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, default='G1iSCA', max_length=6, verbose_name='شناسه کارمندی'),
        ),
    ]
