# Generated by Django 4.0 on 2022-01-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customer_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
    ]
