# Generated by Django 4.0 on 2022-01-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'کارفرما', 'verbose_name_plural': 'کارفرمایان'},
        ),
    ]
