# Generated by Django 4.0 on 2022-01-22 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دپارتمان')),
                ('description', models.TextField(verbose_name='توضیحات دپارتمان')),
                ('staff_users', models.ManyToManyField(related_name='staff_users', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ارشد')),
            ],
            options={
                'verbose_name': 'دپارتمان',
                'verbose_name_plural': 'دپارتمان ها',
            },
        ),
    ]
