# Generated by Django 4.0 on 2022-01-22 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='staff_users',
            field=models.ManyToManyField(blank=True, related_name='staff_users', to=settings.AUTH_USER_MODEL, verbose_name='کاربران ارشد'),
        ),
    ]
